### ISSUE TITLE
TypeScript缩进的规则是ter-indent而不是indent

### ISSUE THREAD

**Issue by xiaosan666** [AlloyTeam/tslint-config-alloy#1]
https://github.com/AlloyTeam/tslint-config-alloy/blob/master/index.js 227行，应该改为："ter-indent": [true, 2]

**Comment by dntzhang** [comment]
@xcatliu

**Comment by xcatliu** [comment]
ter-indent 是一个 tslint 插件（tslint-eslint-rules）提供的功能。不是 tslint 官方提供的功能。
tslint-config-alloy 目前还不包含 tslint-eslint-rules，后面会考虑加上。

**Comment by xiaosan666** [comment]
ok
